# Generated by Django 4.0.4 on 2022-12-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('storage', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('battery_capacity', models.IntegerField()),
                ('screen_size', models.FloatField()),
                ('os', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('camera', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phone')),
            ],
        ),
    ]
